Update script_flash

diff --git a/script_flash b/script_flash
--- a/script_flash
+++ b/script_flash
@@ -1,24 +1,31 @@
-# Definir os caminhos
+#!/bin/bash
+# Dependencies: FLASH
+# Install:
+#   conda install -c bioconda flash
+
+# Define paths
 FASTQ_PATH="/temporario2/9290665/DADOS_ALZHEIMER/laske/cleaned_reads"
 OUTPUT_PATH="/temporario2/9290665/DADOS_ALZHEIMER/laske/outputs_flash"
 
-# Criar a pasta de saída, se não existir
+# Create the output directory if it doesn't exist
 mkdir -p "$OUTPUT_PATH"
 
-# Loop para processar todos os arquivos *_R1.fastq na pasta FASTQ_PATH
+# Loop through all *_R1.fastq files in the FASTQ_PATH
 for FILE1 in "$FASTQ_PATH"/*_R1.fastq; do
-  # Obter o nome base da amostra (remover o sufixo _R1.fastq)
+  # Get the base name of the sample (remove the _R1.fastq suffix)
   BASENAME=$(basename "$FILE1" _R1.fastq)
 
-  # Definir o arquivo correspondente para o par _R2.fastq
+  # Define the corresponding file for the _R2.fastq pair
   FILE2="${FASTQ_PATH}/${BASENAME}_R2.fastq"
 
-  # Verificar se o arquivo _R2.fastq existe
+  # Check if the _R2.fastq file exists
   if [ -f "$FILE2" ]; then
-    # Merging com FLASH
-    flash -m 20 -M 150 --to-stdout "$FILE1" "$FILE2" > "${OUTPUT_PATH}/${BASENAME}.merged.fastq" #m20: baseado no min de merge do fastp que é 30 e o default do flash que é 10. 
-# -M 150: evita o WARNING do FLASH dizendo que muitas sequencias se sobrepoe mais que o parametro porem nao mudou a porcentagem de merge 
+    # Merging with FLASH
+    flash -m 20 -M 150 --to-stdout "$FILE1" "$FILE2" > "${OUTPUT_PATH}/${BASENAME}.merged.fastq" 
+    # -m 20: based on the minimum merge of fastp, which is 30, and the default of FLASH, which is 10.
+    # -M 150: avoids the WARNING from FLASH saying that many sequences overlap more than the parameter, but it didn't change the merge percentage
   else
-    echo "Par do arquivo $FILE1 não encontrado: $FILE2" >&2
+    echo "Pair for file $FILE1 not found: $FILE2" >&2
   fi
 done
+
